### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jeffjewiss** [colettewilson/simpleStarRating#1]
Hi, thanks for creating this plugin.

I tried using this (v0.1.3) with Sanity v2.1.0 and hit an error when trying to start my server:

```
Error in ./node_modules/sanity-plugin-simple-star-rating/lib/index.js
Module not found: Error: Can't resolve '@sanity/components/lib/labels/DefaultLabel'
```

Is this maybe due to the babel build step or not having `@sanity/components` as a dependency?

Thanks!

**Comment by colettewilson** [comment]
Hey, apologies for the delay in my response. The issue is resolved now.
